### ISSUE TITLE
firstDupliacate

### ISSUE THREAD

**Issue by zhyysj** [AlexisWolfWaisman/CodeFights#1]
hi.
I see the code of firstDupliacate, it is great. can you  explain ？I don't quite understand。
thank you!

**Comment by AlexisWolfWaisman** [comment]
Dear @zhyysj  i've updated my code with comments... i tried to explain everything i used to solve the problem. thanks for warn! otherwise maybe it would remains in blank.  
Greetings.-

**Comment by zhyysj** [comment]
Thank you very much.
I Understand it.You are amazing.




------------------ 原始邮件 ------------------
发件人: "Alexis Wolf"<notifications@github.com>;
发送时间: 2019年4月20日(星期六) 凌晨4:59
收件人: "AlexisWolfWaisman/CodeFights-spanish"<CodeFights-spanish@noreply.github.com>;
抄送: "张海燕（北理工珠海学院）"<2552974138@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [AlexisWolfWaisman/CodeFights-spanish] firstDupliacate (#1)




Closed #1.
